### ISSUE TITLE
varIncProb.R

### ISSUE THREAD

**Issue by EoghanONeill** [BelindaHernandez/bartBMA#2]
Should varIncProb.R give the Posterior inclusion probabilities? If yes, then I think the code should be
varIncProb<-function(object,...){
  #object will be bartBMA object.
  imp_vars2=get_weighted_var_imp(num_vars=object$numvars,BIC=object$bic,sum_trees=object$sumoftrees)
  res<-apply((imp_vars2[[3]]>0)*imp_vars2[[1]],2,sum)
  #create varImpPlot command
  class(res)<-"varIncProb.bartBMA"
  res
}

**Comment by BelindaHernandez** [comment]
I just double checked this code on an example and no I think the way it is is correct i.e. this function should give the weighted proportion of times that each variable is chosen over the sum if trees and its total should sum to 1
