### ISSUE TITLE
Columns of tree matrices and depth of nodes; Incorrect depth in get_tree_prior

### ISSUE THREAD

**Issue by EoghanONeill** [BelindaHernandez/bartBMA#4]
This is really two separate issues:

1. Some node numbers appear to first occur in the incorrect columns of tree matrices (if the column number corresponds to the depth).

2. get_tree_prior considers the initial node to be at depth 1, but Chipman et al. (2010) consider this to be depth 0 (d=0,1,2,...).

Chipman, H. A., George, E. I., & McCulloch, R. E. (2010). BART: Bayesian additive regression trees. The Annals of Applied Statistics, 4(1), 266-298.

```
library(devtools)
install_github("EoghanONeill/bartBMA")
library(bartBMA)

#issue: columns and tree depth
# it can be seen in the get_tree_prior function C++ code that 
#columns of tree matrices should correspond to the depth of trees.
#However, it is possible to find examples where indices for splits do not first occur
#in a column corresponding to the correct depth.

#Example:

set.seed(11)
N <- 1000
set.seed(100)
x1 <- runif(N)
x2 <- runif(N)
x3 <- runif(N)
x4 <- runif(N)
x5 <- runif(N)
x6 <- runif(N)
x7 <- runif(N)
x8 <- runif(N)
x9 <- runif(N)
x10 <- runif(N)
epsilon <- rnorm(N)

xcov <- cbind(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10)
y <- sin(pi*x1*x2) + 20*(x3-0.5)^2+10*x4+5*x5+epsilon

bart_bma_example <- bartBMA(x.train = xcov, y.train = y)

#We can read the following tree table and find out the depths of each node
bart_bma_example[[2]][[1]][[1]]
#Node 1, depth 1 (0)
#Node 2, depth 2 (1)
#Node 3, depth 2 (1)
#Node 4, depth 3 (2)
#Node 5, depth 3 (2)
#Node 6, depth 3 (2)
#Node 7, depth 3 (2)
#Node 8, depth 4 (3)
#Node 9, depth 4 (3)
#Node 10, depth 4 (3)
#Node 11, depth 4 (3)

#However, consider the leftmost columns of the tree matrices in which the indices for the nodes occur
# The column numbers should equal the node depths
bart_bma_example[[3]][[1]][[1]] 
#Node 1. column 1
#Node 2. column 2
#Node 3. column 2
#Node 4. column 3
#Node 5. column 3
#Node 6. column 4
#Node 7. column 4
#Node 8. column 4
#Node 9. column 4
#Node 10. column 5
#Node 11. column 5

#Nodes 6 and 7 should first occur in column 3 (replacing 3)
#Nodes 10 and 11 should occur in column 4 (replacing 7)
#There should not be a column 5. (and there should not be zeros in a column)

#Now, assuming the tree table gives the correct description of the tree,
# we can compare the true tree prior to that obtained from get_tree_prior

#Also, the depth used by get_tree prior might be incorrect
# in line 581 of BARTBMA_SumTreeLikelihood.cpp, 1 is added to the column index.
#However, in the description of the prior in Chipman et al. (2010), 
#the depth variable starts at zer0, d=0,1,2,3,...
#Therefore the first column of the tree matrix corresponds to depth zero (d=0).

alpha=0.95
beta=1

#true tree (structure) prior:
alpha*((0+1)^(-beta))*alpha*((1+1)^(-beta))*alpha*((1+1)^(-beta))*alpha*((2+1)^(-beta))*alpha*((2+1)^(-beta))

#prior returned by get_tree_prior
get_tree_prior(bart_bma_example[[2]][[1]][[1]], bart_bma_example[[3]][[1]][[1]] , alpha, beta)
# Accounting for both the error in the tree matrix, and the depth number in get_tree_prior,
# it can be observed that get_tree_prior performs the following (incorrect) calculation:
alpha*((1+1)^(-beta))*alpha*((2+1)^(-beta))*alpha*((2+1)^(-beta))*alpha*((3+1)^(-beta))*alpha*((4+1)^(-beta))


```

**Comment by BelindaHernandez** [comment]
I double checked this example and only found one difference between checking through the data set manually to see which observations should have been assigned to the terminal nodes and which were assigned by BART-BMA. When I run the example above I get a total of 4 sums of trees which each have 5 trees. If we just look at the first tree in the first set i.e. 
> bart_bma_example$sumoftrees[[1]][[1]]
   left daughter right daughter split var split point status        mean std dev
1              2              3         4   0.5037463      1  0.00000000       0
2              4              5         5   0.5094086      1  0.00000000       0
3              6              7         5   0.4392864      1  0.00000000       0
4              0              0         0   0.0000000     -1 -0.18267650       0
5              8              9         4   0.3302243      1  0.00000000       0
6              0              0         0   0.0000000     -1  0.06449881       0
7             10             11         4   0.6882065      1  0.00000000       0
8              0              0         0   0.0000000     -1 -0.09807102       0
9              0              0         0   0.0000000     -1  0.02454284       0
10             0              0         0   0.0000000     -1  0.10010760       0
11             0              0         0   0.0000000     -1  0.24967007       0

Then the only difference I get between manually looking through the data and the assignments BART-BMA made was in its assignment to node 8 (observation 868), however if we round the xcov data set to 7 decimal places it gives the same answer as BART-BMA. If you found other examples let me know, however I can't see any from the example and seed given.

Here is the code I used to search through the tree above:

#take first tree and check assignments of obs to nodes
#node2 
grep(FALSE,which(xcov[,4]<=0.5037463)==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,2]==2))
#node 3
grep(FALSE,which(xcov[,4]>0.5037463)==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,2]==3))

#take node 4 x4<0.504 and x5<=0.509
grep(FALSE,which(xcov[,4]<=0.5037463 & xcov[,5]<=0.5094086 )==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,3]==4))
#take node 5 x4<0.504 and x5>0.509
grep(FALSE,which(xcov[,4]<=0.5037463 & xcov[,5]>0.5094086 )==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,3]==5))

#node 6
grep(FALSE,which(xcov[,4]>0.5037463 & xcov[,5]<0.4392864)==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,3]==6))

#node 7
grep(FALSE,which(xcov[,4]>0.5037463 & xcov[,5]>0.4392864)==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,3]==7))

#node 8, get error find that observation 868 is included in BART-BMA but not in dataset
grep(FALSE,which(xcov[,4]<=0.5037463 & xcov[,5]>0.5094086 & xcov[,4]<=0.3302243)==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,4]==8))
#however on closer inspection this is just a rounding error if we round the xcov dataset to 7 decimal places then we get the same answer as BART-BMA
grep(FALSE,which(xcov[,4]<=0.5037463 & xcov[,5]>0.5094086 & round(xcov[,4],7)<=0.3302243)==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,4]==8))

#node 9 
grep(FALSE,which(xcov[,4]<=0.5037463 & xcov[,5]>0.5094086 & round(xcov[,4],7)>0.3302243)==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,4]==9))

#node 10
grep(FALSE,which(xcov[,4]>0.5037463 & xcov[,5]>0.4392864 & xcov[,4]<0.6882065)==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,4]==10))

#node 11
grep(FALSE,which(xcov[,4]>0.5037463 & xcov[,5]>0.4392864 & xcov[,4]>0.6882065)==which(bart_bma_example$obs_to_termNodesMatrix[[1]][[1]][,4]==11))

**Comment by BelindaHernandez** [comment]
I think I've now got to the bottom of this bug...it was a copy paste error in the set_daughter_to_end_mat() function where when the depth of the node to be split is the same as the number of columns in the tree_matrix the code was making a copy of the previous column rather than creating a column of zeros. 

I've updated the code so please feel free to double check if you have time. 

Re the depth of the nodes, in the tree matrix the depth starts at 1 but for calculations regarding the node depth it starts at 0 (unless there is another bug somewhere else?).

The node depth is set using this line: 
d1=unique(find_term_cols(treemat_c,terminal_nodes[0]))

so it find the column index in the tree matrix where the node number is.

**Comment by EoghanONeill** [comment]
The updated code still returns the incorrect tree matrix when I run the R code that I included above. However, when I change set_daughter_to_end_mat() to implement the correction that you suggest, then the tree matrices appear to be correct. I might do some more testing to make sure that this removes the issue.

I include the corrected code for set_daughter_to_end_mat() below:

```
NumericMatrix set_daughter_to_end_mat(double d,NumericMatrix prior_tree_matrix_temp,double left_daughter,NumericVector ld_obs,NumericVector rd_obs){
  int ncol_mat=prior_tree_matrix_temp.ncol();
  arma::mat N=Rcpp::as<arma::mat>(prior_tree_matrix_temp);
  arma::vec colmat=N.col(d);
  NumericVector colmat2=wrap(colmat);
  
  if(d+1==ncol_mat){
    N.insert_cols(ncol_mat,1);
    int nrow_mat=prior_tree_matrix_temp.nrow();
    NumericVector colmatzero(nrow_mat);
    colmatzero[ld_obs]=left_daughter;
    colmatzero[rd_obs]=left_daughter+1;
    colmat=Rcpp::as<arma::vec>(colmatzero);
    N.col(d+1)=colmat;
  }else{
    //else just update existing column
    colmat2[ld_obs]=left_daughter;
    colmat2[rd_obs]=left_daughter+1;
    colmat=Rcpp::as<arma::vec>(colmat2);
    N.col(d)=colmat;  
  }
  
  return(wrap(N));
}
```

Aside: I wonder if there is also an error in find_obs_to_update_grow . For the following code:

```
if(prior_tree_matrix_temp.ncol()>d+1){								// If the number of columns is greater than d+1
		arma::mat M=Rcpp::as<arma::mat>(prior_tree_matrix_temp);		// M equals arma mat copy of the matrix
		M.insert_cols(prior_tree_matrix_temp.ncol(),1);  				// insert one column after last column
		NumericMatrix prior_tree_matrix=as<NumericMatrix>(wrap(M));		// convert back to NumericMatrix and save as prior_tree_matrix
	}
```

perhaps the condition should be reversed, i.e. the code should be

```
if(prior_tree_matrix_temp.ncol()<=d+1){								// If the number of columns is greater than d+1
		arma::mat M=Rcpp::as<arma::mat>(prior_tree_matrix_temp);		// M equals arma mat copy of the matrix
		M.insert_cols(prior_tree_matrix_temp.ncol(),1);  				// insert one column after last column
		NumericMatrix prior_tree_matrix=as<NumericMatrix>(wrap(M));		// convert back to NumericMatrix and save as prior_tree_matrix
	}
```

but I haven't found any examples where the current find_obs_to_update_grow() code leads to incorrect output.

Aside: I think that the code for set_tree_to_middle() could be made clearer by changing the following line:

```
		if(prior_tree_table_temp(node_to_update[i],0) && prior_tree_table_temp(node_to_update[i],1)!=0){	// What logical condition is to the left of &&? Is this a mistake?
```
to
```
		if((prior_tree_table_temp(node_to_update[i],0)!=0) && (prior_tree_table_temp(node_to_update[i],1)!=0)){
```

The second issue regarding the node depth refers to get_tree_prior and in particular the following line:

```
        int_nodes_index[index_count]=j+1;
```

which I think should be

```
        int_nodes_index[index_count]=j;
```

**Comment by BelindaHernandez** [comment]
Hi Eoghan

Yes you are correct about the tree prior I hadn't noticed that line where 1 was added on again (it shouldn't have been). Also I think you are correct on the other issues here too i.e. the typo in the find_obs_to_update_grow yes I think it should be <= not >. Thanks I'll close this issue now and am starting to go through the rest of the comments and changes
