### ISSUE TITLE
Ordering of trees to keep in Occam's window

### ISSUE THREAD

**Issue by EoghanONeill** [BelindaHernandez/bartBMA#7]
In BARTBMA_SumTreeLikelihood.cpp , possibly the incorrect models are kept in Occam's window in the following functions:

get_best_split [lines 1026-1044]
get_best_split_sum [lines 1238-1256]
get_best_trees [lines 1815-1837]
get_best_trees_sum [lines 2070-2093]

Consider the lines 1026-1044:

```
if(testlik.size()>maxOWsize){
				IntegerVector owindices=order_(testlik);
				owindices=owindices-1;
				//get the top maxOWsize indices to keep in OW
				NumericVector temp_olik(maxOWsize);
				List temp_otrees(maxOWsize);
				List temp_omat(maxOWsize);
				IntegerVector temp_oparent(maxOWsize);
				for(int t=0;t<maxOWsize;t++){
					temp_olik[t]=testlik[owindices[t]];
					temp_otrees[t]=testtree[owindices[t]];
					temp_omat[t]=testmat[owindices[t]];
					temp_oparent[t]=testpar[owindices[t]];
				}
				testlik=temp_olik;
				testtree=temp_otrees;
				testmat=temp_omat;
				testpar=temp_oparent;
			}
```

The function order_() gives a vector in which the first element is the position of the largest element of the input vector, the second element is the position of the second largest element, and so on.
Therefore, I think the maxOWsize LARGEST BIC models are kept in this code. Is it not preferable to keep the smallest BIC models? i.e. use a function that gives the position of the smallest element first instead of the function order()?

Also, the models kept by this code are now ordered descending (i.e. beginning with the largest BIC model), but perhaps it is preferable to order ascending.

**Comment by EoghanONeill** [comment]
I suggest adding the following function:

```
//######################################################################################################################//

// [[Rcpp::export]]

IntegerVector orderforOW(NumericVector x) {	// gives vector of position of smallest value, then position of second smallest value, and so on.
  NumericVector sorted = clone(x).sort();		// sorted is x in ascending order
  //std::reverse(sorted.begin(), sorted.end()); // reverse so that it is in descending order. Could use one line with std::sort(clone(x).begin(), clone(x).end(), std::greater<>())
  
  return match(sorted, x);	//  match is the Rcpp sugar version of the R function match, which returns a vector of the positions of the first matches of the first argument in the second.
}
```

and replacing order_() with orderforOW() in some, but not all cases. In particular, order() should NOT be replaced in the evaluate_model_occams_window() code, or in the gridCP() code.

**Comment by BelindaHernandez** [comment]
you're completely right....I never spotted this as the MaxOWsize was always bigger than the number of models assessed. Thankfully this didn't affect the results of the paper!!
